### ISSUE TITLE
Product Category Make Term Primary selector is gone

### ISSUE THREAD

**Issue by coes123** [rankmath/seo-by-rank-math#10]
**Describe the bug**
There used to be a radio button to select the subcategory you wanted for any given product. I have been using it no problem, even last night.
This morning my plugin updated to 1.0.48 and that radio button is gone. 

I'm referring to this (borrowing this screenshot from a previous forum entry, but it's not the same issue)

![Screen Shot 2019-07-03 at 14 02 49](https://user-images.githubusercontent.com/8754843/94345863-25cd6480-ffe6-11ea-9283-d7be59e2b3d9.png)

**Comment by surajv** [comment]
Hi @coes123,

Thank you for the reporting this issue. We have fixed it internally and will release the new update shortly.
