### ISSUE TITLE
Instagram link in the social networks section

### ISSUE THREAD

**Issue by 79ho3ein** [rankmath/seo-by-rank-math#100]
hello
Please add the Instagram link to the social meta section. This item is available in the yoast plugin.
This is very useful  https://prnt.sc/1xezkea

thank you

**Comment by pratikmts** [comment]
Hello,

Earlier we used to provide an option in Social settings to add Instagram, Pinterest, etc page URLs but later we removed it as Google no longer uses this information from Structured data. Please read here: https://i.rankmath.com/Ut3CGr

Still, if you want to add the Instagram URL in the Structured data then please use the following code:
`
add_filter( 'rank_math/json_ld', function( $data, $jsonld ) {
	if ( ! isset( $data['Organization'] ) ) {
		return $data;
	}
	$data['Organization']['sameAs'][] = 'Instagram_URL';
	return $data;
}, 99, 2 );
`

I hope that helps.

**Comment by 79ho3ein** [comment]
Thank you @pratikmts
