### ISSUE TITLE
Please match rank math with elementor.

### ISSUE THREAD

**Issue by 79ho3ein** [rankmath/seo-by-rank-math#101]
hello
Please coordinate with elementor. Currently, by activating the yoast plugin https://prnt.sc/1xf5vam, the elementor breadcrumbs widget is activated.
Unfortunately, this is not possible for rank math. Please add this compatibility if possible.
thanks

**Comment by surajv** [comment]
Hello @79ho3ein, our Rank Math PRO version offers a similar type of Breadcrumb widget for Elementor.

I hope that helps.
