### ISSUE TITLE
Support ImageMagick?

### ISSUE THREAD

**Issue by huubl** [rankmath/seo-by-rank-math#103]
Hi,

Does Rank Math work with the ImageMagick instead of the GD Extension?

If so maybe ImageMagick support van be added to:
https://github.com/rankmath/seo-by-rank-math/blob/82f5962022efea196ccabc0fd6cd7f23301254ec/includes/admin/wizard/views/compatibility.php#L24

**Comment by balazsmts** [comment]
Hello @huubl,

Rank Math requires the GD extension for [the watermark/icon overlay option](https://rankmath.com/kb/watermark-for-social-sharing/). It is not compatible with ImageMagick.
