### ISSUE TITLE
Rank Math showing error on setup wizard

### ISSUE THREAD

**Issue by abdulhadicse** [rankmath/seo-by-rank-math#104]
**Describe the bug**
I wanted to install the plugin for the first time I got the error message something like [this](https://prnt.sc/20ly41k).

**To Reproduce**
1. Install and active the plugin and you will see the error message

**Screenshots**
[https://prnt.sc/20ly41k](https://prnt.sc/20ly41k)

**Comment by pratikmts** [comment]
Hi @abdulhadicse 

This issue was in the CMB2 package which we use in the Rank Math plugin. Please update the plugin to the latest version. You should no longer get this error.

**Comment by pratikrm** [comment]
Closing it due to inactivity. Please reopen it if you still get this error.
