### ISSUE TITLE
Divi data collector should not use absolute-path reference

### ISSUE THREAD

**Issue by romainbriand** [rankmath/seo-by-rank-math#110]
**Describe the bug**
Divi data collector is using absolute-path reference to `wp-json` which is causing troubles when wordpress is hosted on a subdirectory.

**To Reproduce**

Example 1:
My blog is hosted at `myblog.tld`, no problem

Example 2:
My blog is hosted at `mydomain.tld/blog`, problem!
It will try to reach `mydomain.tld/wp-json` which of course returns 404

**Expected behavior**
In case number 2 it should reach `mydomain.tld/blog/wp-json/`...

**Screenshots**
N/A

**Desktop (please complete the following information):**
- Any

**Smartphone (please complete the following information):**
- Any

**Additional context**
Example of problematic code: https://github.com/rankmath/seo-by-rank-math/blob/eea089f0afe7f476d1f9dadc1a9f75377373d282/assets/admin/src/divi/DataCollector.js#L224

**Comment by pratikmts** [comment]
Hi @romainbriand 

Please update the plugin to the latest version. We have fixed this issue in v1.0.84.

I hope that helps.

**Comment by romainbriand** [comment]
> Hi @romainbriand
> 
> Please update the plugin to the latest version. We have fixed this issue in v1.0.84.
> 
> I hope that helps.

I've noticed it! Thank you! 👍
