### ISSUE TITLE
Tagify input styles broken if another plugin / theme includes tagify

### ISSUE THREAD

**Issue by bfiessinger** [rankmath/seo-by-rank-math#114]
Refering to https://github.com/bfiessinger/wppedia/issues/42

If another plugin uses [tagify](https://yaireo.github.io/tagify/) and includes their default styles while RankMath is installed the tag input for both plugins will look kinda broken.

Maybe RankMath should consider overriding tagify styles with a special class.

```css
.tagify__tag:first-child .tagify__tag-text:before {...}
// ==>
.rm-tagify .tagify__tag:first-child .tagify__tag-text:before {...}
```

![Screenshot 2022-05-03 175306](https://user-images.githubusercontent.com/41627893/166489238-75b82d98-a9bc-4885-aac9-acda9333c72c.png)

**Comment by pratikrm** [comment]
Hello @bfiessinger 

Thank you for letting us know this issue. We have logged it as a bug and we'll release an update soon with the fix.
