### ISSUE TITLE
unclosed HTML tags

### ISSUE THREAD

**Issue by hajakutbudeen-dev** [rankmath/seo-by-rank-math#116]
Hello there,

We are using Rank Math SEO & Rank Math SEO Pro for our WordPress website. we are using cornerstone for page editor. When we save page edit in cornerstone we got error message.
'The element could not render due to invalid markup. You may have unclosed HTML tags in your content'

We disable our all plugins we enable one by one then we found this issue came from Rank Math SEO Free plugin.

Here i mentioned when this issue found:
v1.0.82 - No issue found
v1.0.86 - Issue found
v1.0.87 - Issue found
v1.0.89 - Issue found
v1.0.89.1 - Issue found

We expect you will fix that in next release but still the prob is there. so kindly please verify and fix as soon as possible.
![issue](https://user-images.githubusercontent.com/78490145/169964637-3231c453-e605-4bc0-85c9-76838eef9525.png)

**Comment by pratikrm** [comment]
Hello @hajakutbudeen-dev 

We couldn't reproduce this issue on our setup. Please open a support ticket here [support.rankmath.com](https://support.rankmath.com/)? Our support staff will help you.

Thank you.

**Comment by pratikrm** [comment]
Closing it due to inactivity
