### ISSUE TITLE
`og:image:alt` meta has changed from v1.0.99 to v1.0.100

### ISSUE THREAD

**Issue by strategio** [rankmath/seo-by-rank-math#128]
**Describe the bug**
`og:image:alt` meta has changed from v1.0.99 to v1.0.100

**To Reproduce**
1. Go to the Media library
2. Add a new image with the title "My image title"
3. Edit the image and set "Alternative Text" to "My alternative image content"
4. Display the image page on the frontend
5. Inspect the source

Here's the results:
=> v1.0.99: `<meta property="og:image:alt" content="My alternative image content" />`
=> v1.0.100: `<meta property="og:image:alt" content="My image title" />`

**Additional context**
We have automated end-to-end tests with WPML and this started to fail as soon as we updated to v1.0.100.
If it was a bug that you corrected, we'll have to adjust our tests. Otherwise, if it's a regression on your side, we'll wait for your fix to restore our test.

**WPML internal ref: wpmlwpseo-217**

**Comment by surajv** [comment]
Hi @strategio, sorry for not following up, issue is not happening for us.

In version v1.0.100, we have fixed the related issue, this filter (https://rankmath.com/kb/filters-hooks-api-developer/#change-opengraph-image) was not working. Please check if you are using this filter which is modifying the output.

**Comment by strategio** [comment]
Thanks @surajv, we've restored the failing assertion in our tests and we confirm it's passing again.
