### ISSUE TITLE
Minify  JSON+ld Schema Output 

### ISSUE THREAD

**Issue by codehaveli** [rankmath/seo-by-rank-math#13]
**Is your feature request related to a problem? Please describe.**
The ld+json added by the plugin is not minified

**Describe the solution you'd like**
Minify the JSON+ld  output

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

![image](https://user-images.githubusercontent.com/33904304/95008255-de725400-0635-11eb-9365-bd1f0811eaf7.png)

**Comment by surajv** [comment]
Hi @codehaveli,

Thank you for the suggestion. This will be added to one of our upcoming updates.

I will inform you once it is ready.

**Comment by surajv** [comment]
Fixed in a97f738 (v1.0.56)
