### ISSUE TITLE
Schema Module: Incompatibility with Molongui Authorship

### ISSUE THREAD

**Issue by bmos** [rankmath/seo-by-rank-math#131]
**Describe the bug**
Each of my post pages have an error shows at the top.

`Notice: Undefined index: @id in /home/------/public_html/wp-content/plugins/seo-by-rank-math/includes/modules/schema/class-frontend.php on line 252`

**To Reproduce**
1. Install Rank Math and enable Schema module.
2. Install Molongui Authorship.
3. Set up a guest author.
4. Publish a post with only the guest author listed.
5. Visit the published post. The error will be in the page HTML and visible.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - Browser Firefox
 - Version 106.0.1

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 16.1
 - Browser Safari

**Additional context**
Disabling the Schema module makes the error go away.
I have tried changing a variety of settings in the Schema module and none seem to impact it.
I have submitted a pull request with a small change that solves the incompatibility.

**Comment by bmos** [comment]
![image](https://user-images.githubusercontent.com/1916835/198715743-b8f2ab48-82d0-4133-b186-6854ae75beb9.png)

**Comment by bmos** [comment]
Molongui Authorship

**Comment by bmos** [comment]
The culprit is Molongui Authorship's guest authors as these authors don't have a user id.

**Comment by bmos** [comment]
It looks like fixing this compatibility might be very simple:
https://github.com/rankmath/seo-by-rank-math/blob/master/includes/modules/schema/class-frontend.php#L235-L270

if there is no $temp_data['ProfilePage']['@id'], then return $data

**Comment by bmos** [comment]
```
if ( empty( $data['ProfilePage'] ) || empty( $data['ProfilePage']['@id'] ) || ! is_singular() ) {
			return $data;
		}
```
has fixed this in my local copy

**Comment by bmos** [comment]
thanks!

**Comment by bmos** [comment]
Can someone take a look at this? This change should not cause any significant performance or compatibility issues.

**Comment by pratikrm** [comment]
Hi @bmos 

Thank you for creating a Pull request. We'll make sure to include the changes in the next update.
