### ISSUE TITLE
Not such a big issue, but could be confusing...

### ISSUE THREAD

**Issue by ParagonExpressions** [rankmath/seo-by-rank-math#14]
**Describe the bug**
After re-authenticating Google account, the notification at the top is still showing. This could be confusing for those who connected to Google and are still wondering why it's saying to re-authenticate. 

**To Reproduce**
**Expected behavior**
I expected that once you re-authenticate, that the yellow warning would disappear on the top. 

**Screenshots**
<img width="1297" alt="Screen Shot 2020-10-09 at 10 51 21 AM" src="https://user-images.githubusercontent.com/72603824/95569391-6f25a700-0a1d-11eb-8513-f4ba1d74a47b.png">

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.6
 - Browser: Chrome
 - Version: 85.0.4183.121 

**Additional context**

**Comment by ParagonExpressions** [comment]
Maybe something is wrong, or because it is just a beta, but I also do not show any data. Just because of Beta or is something not configured correctly? I am using the Jupiter X theme, and was previously Google ID through their theme, and since have deactivated. My site still seems to be connected with Google analytics as I am able to see live traffic. 
<img width="1323" alt="Screen Shot 2020-10-09 at 2 31 32 PM" src="https://user-images.githubusercontent.com/72603824/95589237-5e385e00-0a3c-11eb-9964-c390247645be.png">
<img width="1318" alt="Screen Shot 2020-10-09 at 2 31 22 PM" src="https://user-images.githubusercontent.com/72603824/95589239-5e385e00-0a3c-11eb-9852-2540da5a6d54.png">
![Uploading Screen Shot 2020-10-09 at 2.31.11 PM.png…]()

**Comment by surajv** [comment]
Hi, could you please confirm if Google Search Console and Google Analytics settings are properly configured in the Settings page?

**Comment by ParagonExpressions** [comment]
I'm seeing the screen shot of the only setting page. Am I missing something? Both are saying they are green, and have the correct site listed
<img width="940" alt="Screen Shot 2020-10-09 at 3 35 22 PM" src="https://user-images.githubusercontent.com/72603824/95596325-2681e400-0a45-11eb-87e3-ee05ffe8b4fd.png">

**Comment by ParagonExpressions** [comment]
I should add that I also tried it in troubleshoot mode with "site health" and the exact same thing showed up. No data, and also the yellow banner suggesting to reactivate google. I've tried disconnecting and reconnecting. You are welcome to go on and take a look.

**Comment by surajv** [comment]
Notice issue will be fixed in the next beta update, regarding the data, could you please check if the site is selected in the Search Console Option?

**Comment by ParagonExpressions** [comment]
Yes it is.
<img width="1254" alt="Screen Shot 2020-10-09 at 3 49 10 PM" src="https://user-images.githubusercontent.com/72603824/95597798-00f5da00-0a47-11eb-8adc-bd79ed49014e.png">

**Comment by surajv** [comment]
Do you have WooCommerce installed? If not please head over to **WP Dashboard >> Tools >> Scheduled Actions** and check the Pending section, is there any Rank Math related task pending? 

Are there any completed tasks in the 'completed' section?

**Comment by ParagonExpressions** [comment]
No I do not have woocommerce

**Comment by surajv** [comment]
Please follow the steps from my last reply to see if there are completed or pending Rank Math scheduled actions.

**Comment by ParagonExpressions** [comment]
An I missing something? I don't seem to have scheduled actions...
<img width="1187" alt="Screen Shot 2020-10-09 at 4 37 47 PM" src="https://user-images.githubusercontent.com/72603824/95603189-d8bda980-0a4d-11eb-86db-735749bd117f.png">

**Comment by surajv** [comment]
That's strange, is this a multisite? Please try accessing this page directly `wp-admin/tools.php?page=action-scheduler`

**Comment by ParagonExpressions** [comment]
Ya, that is interesting. I wonder why it wasn't there??? It is not a multi-site. Anyways I was able to access the page directly and yes there is one pending related to rankmath, 
![Screen Shot 2020-10-09 at 5 32 11 PM](https://user-images.githubusercontent.com/72603824/95608760-854f5980-0a55-11eb-9279-b6cf7b612ada.png)

Thanks for your help

**Comment by ParagonExpressions** [comment]
and a completed task. 
![Screen Shot 2020-10-09 at 5 32 11 PM](https://user-images.githubusercontent.com/72603824/95608900-c0ea2380-0a55-11eb-96e0-2d4c9c5f3310.png)

**Comment by surajv** [comment]
It looks like data fetch didn't start on first connect. Please head over the **Rank Math >> General Settings >> Analytics** and click the **Update Data manually** button

**Comment by ParagonExpressions** [comment]
Fetching in Progress. I'll update when its finished. Thanks.

**Comment by surajv** [comment]
Sure, you can navigate from that page as this is a background process.

**Comment by ParagonExpressions** [comment]
working! Great thanks. And it should auto update now correct?

**Comment by surajv** [comment]
Yes, it should, also we found the issue which was breaking the first fetch after connecting Google accounts. It will be fixed in the final release.

Thank you for reporting it!

**Comment by surajv** [comment]
Hi @ParagonExpressions, we have released the stable version, please update and check.

Thank you.

**Comment by ParagonExpressions** [comment]
Hey Surajv, Thanks so much for working with me on this! Love the customer service you have for the free version. I'll be sure to purchase the pro when it comes out... 

Just to update you I needed to manually fetch the analytics again. Not sure why that is on my site.

**Comment by ParagonExpressions** [comment]
ALSO... Something seems weird here. In my stats it says that I have 19 keywords in the top 1-3 but my data only shows 1 
![Screen Shot 2020-10-12 at 11 44 16 AM](https://user-images.githubusercontent.com/72603824/95737883-46511c00-0c80-11eb-84d2-a44fda77584d.png)

**Comment by surajv** [comment]
That's strange. Could you please try clearing the Analytics Cache from the Rank Math > Status & Tools > Clear Cache? And then try hard refreshing the browser cache.

**Comment by ParagonExpressions** [comment]
Hmmm... No that doesn't seem to have fixed it. Should I try to rebuild index or remove Rank Math transients?

**Comment by ParagonExpressions** [comment]
Is this also normal? The fact that I have nothing in the "content" section? 
![Screen Shot 2020-10-12 at 2 44 56 PM](https://user-images.githubusercontent.com/72603824/95753471-925c8a80-0c99-11eb-9121-e70e058618d3.png)

**Comment by ParagonExpressions** [comment]
UPDATE: I've tried caching, rebuilding the index, and removing transients. Nothing really has changed. I'm also wondering about my site being ranked for only 1 keyword, but then on the keyword tab it said that 19 keywords are in the top 1-3. Something seems a bit off.

**Comment by surajv** [comment]
Umm, let's try these steps:
1. Reindex posts using our Reindex tool
2. Delete all the data using the 'Delete Data' button in the Analytics setting
3. Click Update Data Manually https://i.rankmath.com/u32W40, wait for the new fetching to complete
4. Purge analytics cache from the tool

**Comment by ParagonExpressions** [comment]
ok. stand by.

**Comment by ParagonExpressions** [comment]
Now it seems that I have lost my "search traffic" stats, and nothing else seems to have been "fixed." Do you think something is set up weird? I am posting a screenshot of my actual google analytics, compared to what Rank math is giving me. And I confirm it is the right property and view.
![Screen Shot 2020-10-12 at 4 17 27 PM](https://user-images.githubusercontent.com/72603824/95763768-69db8d00-0ca7-11eb-843a-2adc2f0f94ab.png)
![Screen Shot 2020-10-12 at 4 19 09 PM](https://user-images.githubusercontent.com/72603824/95763791-706a0480-0ca7-11eb-9598-da31a74846ba.png)

**Comment by ParagonExpressions** [comment]
Should I be posting this somewhere else? I'm not sure if you want me to be doing this in Github or if I should be putting this in the Rankmath help forum. 
Seems like some sort of bug to me though.

**Comment by surajv** [comment]
Our GA API is using almost 100% of the daily quota that might be the reason for no GA data, but Google Search Console data and posts should appear without any issue.

Sure, please open a ticket in our forum, and if possible login details so I can get it investigated by one of our senior developers.

Thank you.

**Comment by ParagonExpressions** [comment]
Okay sounds good. Thanks Surajv
Cheers

**Comment by ash-tsc** [comment]
HI @surajv , HI @ParagonExpressions , I have a similar issue. I can connect but only Search Traffic is never displayed. Everthing else shows. Additionally while connecting "Create new" View results in an undefined view that I cant define a name for or connect to. I can connect to exsisting Views but Search traffic is never displayed. Take care!
![1](https://user-images.githubusercontent.com/16594981/95975704-c90bdf80-0e16-11eb-882a-ae54ea9da945.png)

**Comment by ash-tsc** [comment]
HI One more ote. Not sure if its my issue but maybe installing an additional analytics code if another code is already exsistong is problematic?
see:
https://support.google.com/webmasters/thread/16975591?hl=en
I just spotted that you have implemented the GA tracking code twice, the other time with the correct account id. But it looks like only the first and incorrect one is firing. Remove the broken tag and things should start working again.

Site kit does not have the issue and shows all information. Best,

**Comment by ParagonExpressions** [comment]
Hey there, thanks @ash-tsc  for this info. I'm continuing on in this discussion here also even though I have not heard a response on the actual support yet. I thought that there might be a conflict with another previous google analytics js might be still on the site. gtag.js, or googleanalytics.js After using a google analytics debugger, I confirm that there is indeed another tracking code. However, I have checked all of my plug-ins and theme and cannot discover where it is coming from. 

![Screen Shot 2020-10-14 at 2 00 26 PM](https://user-images.githubusercontent.com/72603824/95992223-a33a0700-0e25-11eb-8cfa-0897cac67f5a.png)


I also have received php errors in logs everyday: 

[13-Oct-2020 10:52:29 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'traffic AS (
			    SELECT t1.page as page, COALESCE( t1.pageviews, 0 ) as pagev' at line 1 for query WITH traffic AS (
			    SELECT t1.page as page, COALESCE( t1.pageviews, 0 ) as pageviews, COALESCE( t2.pageviews - t1.pageviews, 0 ) as difference
				FROM
			    	( SELECT page, SUM(pageviews) as pageviews FROM pecomrank_math_analytics_ga WHERE 1=1 AND created BETWEEN '2020-09-05 00:00:01' AND '2020-10-10 23:59:59' GROUP BY page ) as t1
				LEFT JOIN
			    	( SELECT page, SUM(pageviews) as pageviews FROM pecomrank_math_analytics_ga WHERE 1=1 AND created BETWEEN '2020-07-31 00:00:01' AND '2020-09-04 23:59:59' GROUP BY page ) as t2
				ON t1.page = t2.page
			)
			SELECT SQL_CALC_FOUND_ROWS o.*, COALESCE( t.pageviews, 0 ) as pageviews, COALESCE( t.difference, 0 ) as difference
			FROM pecomrank_math_analytics_objects as o
			LEFT JOIN traffic as t ON o.page = t.page
			ORDER BY pageviews DESC
			LIMIT 0, 25 made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, RankMath\Analytics\Posts->get_posts_rows_by_pageviews, RankMath\Analytics\Pageviews->get_pageviews_with_object

**Comment by ash-tsc** [comment]
Hey @surajv, any feedback regarding this issue? Is it mandatory for rank math analytics  to work to not install two different analytics codes? How can I removed the code that I additionally installed via rank math? Thx!

**Comment by surajv** [comment]
Hi @ash-tsc,

If this option is disabled https://i.rankmath.com/lgOroI, then we don't add any analytics tracking code in the frontend. If you are using any third-party plugin to insert analytics code, then you can disable this option.

I hope this helps.

If you still have any issues, please create a support ticket in our support forum.

Thank you.
