### ISSUE TITLE
Bug strpos() in image seo

### ISSUE THREAD

**Issue by Rayiumir** [rankmath/seo-by-rank-math#142]
Hi...
I have had this error on my website for several months and you still haven't fixed it.

` Warning: strpos() expects parameter 1 to be string, array given in /home/public_html/wp-content/plugins/seo-by-rank-math-pro/includes/modules/image-seo/class-image-seo-pro.php on line 106

Warning: strpos() expects parameter 1 to be string, array given in /home/public_html/wp-content/plugins/seo-by-rank-math-pro/includes/modules/image-seo/class-image-seo-pro.php on line 106

Warning: strpos() expects parameter 1 to be string, array given in /home/public_html/wp-content/plugins/seo-by-rank-math-pro/includes/modules/image-seo/class-image-seo-pro.php on line 106

Warning: strpos() expects parameter 1 to be string, array given in /home/public_html/wp-content/plugins/seo-by-rank-math-pro/includes/modules/image-seo/class-image-seo-pro.php on line 106

Warning: strpos() expects parameter 1 to be string, array given in /home/public_html/wp-content/plugins/seo-by-rank-math-pro/includes/modules/image-seo/class-image-seo-pro.php on line 106

Warning: strpos() expects parameter 1 to be string, array given in /home/public_html/wp-content/plugins/seo-by-rank-math-pro/includes/modules/image-seo/class-image-seo-pro.php on line 106`

**Comment by obedparla** [comment]
That seems to be a but with RankMath SEO. It may show up in our builder but the error is not in our files
