### ISSUE TITLE
Action scheduler library needs an update

### ISSUE THREAD

**Issue by shazzad** [rankmath/seo-by-rank-math#145]
**Describe the bug**
Currently used "woocommerce/action-scheduler": "3.4.2" library shows a debug notice inside admin screen.
Which they have solved in recent update (3.5.4).
https://github.com/woocommerce/action-scheduler/pull/868

**To Reproduce**
1. Go to 'Wp Admin'
2. Make sure wordpress transient named `action_scheduler_last_pastdue_actions_check` have any value.
3. See error

**Screenshots**
![Rankmath Action Scheduler Debug Notice](https://user-images.githubusercontent.com/2789126/212748124-bb7fe244-172c-4c66-a45f-d976ae148890.png)

**Comment by nieelu** [comment]
I am also seeing this issue. Would love to see it updated.

**Comment by surajv** [comment]
Hi @shazzad & @nieelu, thank you for reporting this issue, we have fixed it in v1.0.107
