### ISSUE TITLE
Warning strpos() expects parameter 1 to be string

### ISSUE THREAD

**Issue by RaymondTomcat** [rankmath/seo-by-rank-math#148]
Hi...
I have had this error on my website for several months and you still haven't fixed it.

` Warning: strpos() expects parameter 1 to be string, array given in /home/public_html/wp-content/plugins/seo-by-rank-math-pro/includes/modules/image-seo/class-image-seo-pro.php on line 106`

**Comment by uzair-b** [comment]
We just wanted to inform you that we have released an update with a fix. 

Please update Rank Math & all other plugins, themes and WordPress to the latest version.

**Comment by RaymondTomcat** [comment]
@uzair-b 
hi ...
Thank you for your answer
