### ISSUE TITLE
Breadcrumb post-type output singular_name, not its name.

### ISSUE THREAD

**Issue by thetoine** [rankmath/seo-by-rank-math#15]
Hi,

Quick question regarding the post-type display in breadcrumb. The code seems to output the `singular_name`, should this not display the `name` instead ?

```
/ Home / My PostType
/ Home / My PostType / My title
```

Should instead display :

```
/ Home / My PostTypes
/ Home / My PostTypes / My title
```

https://github.com/rankmath/seo-by-rank-math/blob/653b0e055c5cecf02dfc683f7964f1e1db121ad0/includes/frontend/class-breadcrumbs.php#L385

Is this someting by design? I think this could be a great option to add in the Breadcrumb options. I'm glad to contribute on that feature if needed.

Thank you, best regards.

PS: We really really love your plugin, it's amazing with a stellar code structure.

**Comment by thetoine** [comment]
Actually, patching this new setting took me 10 minutes. Ping me if you want a PR for that.

**Comment by surajv** [comment]
Hello @thetoine,

Thank you for opening your first issue, really appreciate that.

Currently, we are little occupied with the PRO version. Once that is released, we will revisit this issue.

Thank you.

**Comment by thetoine** [comment]
Hello @surajv,

Are you open to pull requests for new features? I can work on the feature on my side.

**Comment by surajv** [comment]
Sure. That would be appreciated.

As long as the code is written according to WordPress Codex and is secure, we can definitely get that included in the plugin.
If you have any questions, please let me know.

Thank you.

**Comment by surajv** [comment]
Closing it for inactivity. Please feel free to open a new issue along with the PR.
