### ISSUE TITLE
Site Crashed after the install

### ISSUE THREAD

**Issue by KredoDesign** [rankmath/seo-by-rank-math#16]
Just had to delete Rank Math from my cpanel as it crashed my site....

**Comment by surajv** [comment]
Hello @KredoDesign,

Please refer to this document https://rankmath.com/kb/fatal-error-after-1-0-49-update/

**Comment by surajv** [comment]
Hello @KredoDesign,

Have you managed to solve the issue by using the above solution?

**Comment by surajv** [comment]
Closing it for inactivity.
