### ISSUE TITLE
Adding new Site in Multi-Site

### ISSUE THREAD

**Issue by asparatu** [rankmath/seo-by-rank-math#17]
when I try to make a new site in the mutli-domain, I get this error. I see you have a fix for it, but I don't know where need to change to make it work.

**Describe the bug**
`Fatal error: Uncaught Exception: Error saving action: Table 'db.wp_5_actionscheduler_actions' doesn't exist
in html_public/wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 75

Call stack:

ActionScheduler_DBStore::save_action()
wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler/classes/ActionScheduler_ActionFactory.php:177
ActionScheduler_ActionFactory::store()
wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler/classes/ActionScheduler_ActionFactory.php:105
ActionScheduler_ActionFactory::recurring()
wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler/functions.php:54
as_schedule_recurring_action()
wp-content/plugins/seo-by-rank-math/includes/modules/analytics/class-installer.php:35
RankMath\A\Installer::install()
wp-content/plugins/seo-by-rank-math/includes/class-installer.php:170
RankMath\Installer::activate()
wp-content/plugins/seo-by-rank-math/includes/class-installer.php:82
RankMath\Installer::activate_blog()
wp-includes/class-wp-hook.php:289
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:311
WP_Hook::do_action()
wp-includes/plugin.php:544
do_action_ref_array()
wp-includes/plugin.php:660
do_action_deprecated()
wp-includes/ms-site.php:139
wp_insert_site()
wp-includes/ms-functions.php:1398
wpmu_create_blog()
wp-admin/network/site-new.php:140`

**Comment by surajv** [comment]
Hi @asparatu, please refer to this KB document https://rankmath.com/kb/fatal-error-after-1-0-49-update/

**Comment by asparatu** [comment]
> Hi @asparatu, please refer to this KB document https://rankmath.com/kb/fatal-error-after-1-0-49-update/

I did what the KB said but didn't fix it. I see what is causing the problem. When I added a new site in WordPress Multi-Site (i am using subfolders, not subdomains) Math Rank does create these tables. also, I do not have woocommerce installed on site.

**Comment by surajv** [comment]
That’s disappointing and sorry about that.

Can you please visit the following page where you see the error?

`/wp-admin/admin.php?page=wc-status&tab=action-scheduler`

And see if the missing tables are created afterward.

Looking forward to helping you. Thank you.

**Comment by surajv** [comment]
Hi Shane,

Did this solution work for you?

**Comment by asparatu** [comment]
Hello @surajv 

Sorry for the late reply. I see what is happening, but the link sent me didn't work (Error: Sorry, you are not allowed to access this page.)

When you have Math Rank installed on WPMU and you create new subfolder sites.  Rank Math creates the tables for that new site and does create the other tables. When you enable Rank Math on that subsite the tables that gave the error are created. 

I did notice that when you remove the subsite the Rank Math table do not drop.

So, you might want to make so the tables are only created if the public is enabled or fix so the other tables are created on creation of subfolders site.

**Comment by asparatu** [comment]
I was looking at my logging plugin, I think there is a problem with the SQL script

Component	=>	Unknown
CurrentUserID	=>	1
CurrentUserRoles	=>	array()
EventType	=>	created
Object	=>	database
Severity	=>	6
TableNames	=>	IF

From what i can see the script is trying to create a table called **IF** i am assuming that is for IF..else statement not correctly formated. 

I saw that this happen after the created the all the Rank Math Tables, if that is any help.

**Comment by surajv** [comment]
Hi @asparatu,

Please try adding this PHP file in the `wp-content/mu-plugins` folder: https://github.com/rankmath/_repair-action-scheduler-multisite

After that, please try creating a new site.

**Comment by asparatu** [comment]
Hello @surajv 

That worked. When created the site there were no errors. I checked the database and the tables were added.
Thank you.
