### ISSUE TITLE
404 Redirections to homepage use WP_SITEURL instead of WP_HOMEURL

### ISSUE THREAD

**Issue by amarsyla** [rankmath/seo-by-rank-math#2]
**Describe the bug**
When enabling the Redirections feature and redirecting 404 pages to homepage, the site is redirected to WP_SITEURL instead of WP_HOMEURL. In cases where these 2 urls are different (for example if you're using the Bedrock framework), it causes an infinite redirect loop or just another 404 page. The same thing happens with the default value of Local SEO URL.

**To Reproduce**
1. Enable Redirections from Rank Math dashboard (Advanced Mode)
2. Go to Rank Math > General Settings > Redirections
3. Set Fallback Behavior to Redirect to Homepage
4. Visit a 404 page
5. Instead of redirecting to the site home url, it redirects to the wp site url (in my case domain.com/wp)

**Expected behavior**
Use WordPress homeurl instead of siteurl

**Additional context**
The same issue happens in other settings. One other example is the Local SEO URL in Rank Math > Titles & Meta > Local SEO

**Comment by surajv** [comment]
Hi @amarsyla,

Thank you for reporting the issue, we have fixed it in the latest version v1.0.46.
