### ISSUE TITLE
Shortcodes not converted in rendered meta description and schema's

### ISSUE THREAD

**Issue by CodeBradley** [rankmath/seo-by-rank-math#22]
**Describe the bug**
I have a `[company]` shortcode that dynamically converts into the business name set on my websites. When I use the `[company]` shortcode within my WooCommerce product category meta descriptions it gets indexed on Google with the actual shortcode, `[company]`, instead of my actual business name. 

A matter of fact, I'm not seeing the meta description inserted throughout my website at all now for some reason; so I can't show a screenshot of that. I don't want that to distract from the problem at hand, but ideally I would like to know how to fix both issues if one of the dev's or a knowledgeable community member could assist.

Thanks guy, loving the plugin so far. It's a better approach than Yoast SEO in the Elementor context for sure.

**To Reproduce**

1. Setup WooCommerce category
2. Add meta description's to it using plugin
3. Check the meta description with inspector
4. ???
5. Profit

**Expected behavior**

I expected the shortcode to be ran through do_shortcode function to convert it to my company name.

**Screenshots**
<img width="592" alt="Screen Shot 2020-10-24 at 8 06 07 PM" src="https://user-images.githubusercontent.com/3913066/97096665-06e9de80-1635-11eb-9580-6fda644da5e0.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 86.0.4240.111 (Official Build) (x86_64)

**Additional context**

Side Note: An additional feature I personally would like to see would be for WooCommerce categories built with Elementor's Theme Builder to have the SEO tab in the editor instead, or on top, of us having to go into the actual WooCommerce category.

**Comment by surajv** [comment]
Hi @CodeBradley,

We intentionally stripe shortcodes from the metadata as many shortcodes print HTML, which breaks the front-end design.

If you want to use shortcodes in the metadata, please try the below filter in your theme's functions.php file or using the Code Snippets plugin.

https://rankmath.com/kb/filters-hooks-api-developer/#allow-shortcodes

```
/**
 * Allow shortcodes in the Meta Data.
 */
add_filter( 'rank_math/paper/auto_generated_description/apply_shortcode', '__return_true' );
```

For WooCommerce Products
```
/**
* Filter to allow shortcodes in the Product schema description.
*/
add_filter( 'rank_math/product_description/apply_shortcode', '__return_true' );
```

**Comment by surajv** [comment]
Closing it for inactivity.
