### ISSUE TITLE
Default Article Schema type not added to post structured data

### ISSUE THREAD

**Issue by dawnbirth** [rankmath/seo-by-rank-math#24]
**Describe the bug**
When  the Global settings of Schema Type is set to "Article" and the Article type is also set to "Article" the type applied is "WebPage" and the Article type is not added to the structured data of the posts that don't have a type set from the post editing screen. 

**To Reproduce**

1. Go to 'Titles & Meta' settings page
2. Click on 'Posts' Tab
3. Set the "Schema Type" to Article and "Article Type" to "Article"
4. Save the changes
5. In the browser, open a post that doesn't have a Schema type set in its post meta through the post editing screen.
6. Check the structured data set to this post, it is "WebPage" not "Article".

**Expected behavior**

The global Article type should be applied on posts unless a manual type is specified for the post through the editing screen of that post

**The code causing the issue**
We solved the issue in this file
`includes/modules/schema/snippets/class-singular.php`
By modifying this line
`		$schema = in_array( $schema, [ 'BlogPosting', 'NewsArticle' ], true ) ? 'article' : $schema;`
To
`		$schema = in_array( $schema, [ 'Article', 'BlogPosting', 'NewsArticle' ], true ) ? 'article' : $schema;`

**Comment by MyThemeShop** [comment]
Hello @dawnbirth 

Thank you for reporting the issue, we have fixed that in the latest update.

Please update to it.

We appreciate your patience and understanding in this matter.

Take care!
