### ISSUE TITLE
The string "Make Term Primary" is hardcoded and not translatable

### ISSUE THREAD

**Issue by DAnn2012** [rankmath/seo-by-rank-math#285]
**Describe the bug**
The string "**Make Term Primary**" is hardcoded and not translatable

**Expected behavior**
The "**Make Term Primary**" string should use WordPress' i18n functions and be translatable

**Screenshots**
<img width="288" alt="247857059-b3b42768-ed31-45b7-89e4-667fbb9afe91" src="https://github.com/user-attachments/assets/9bfd593c-5b25-4dd4-8180-01959d12afc9">

https://github.com/rankmath/seo-by-rank-math/blob/84827ce80b23c72e893d527e32d38b9b02ffad48/assets/admin/src/classic/components/PrimaryTerm.js#L35

https://github.com/rankmath/seo-by-rank-math/blob/84827ce80b23c72e893d527e32d38b9b02ffad48/assets/admin/src/classic/components/PrimaryTerm.js#L102

Also in these lines of this file there are hardcoded and untranslatable strings:

https://github.com/rankmath/seo-by-rank-math/blob/84827ce80b23c72e893d527e32d38b9b02ffad48/assets/admin/src/classic/Assessor.js#L77

https://github.com/rankmath/seo-by-rank-math/blob/84827ce80b23c72e893d527e32d38b9b02ffad48/assets/admin/src/classic/Assessor.js#L81

**Comment by DAnn2012** [comment]
Hi @pratikrm 

please could you kindly take a look at this my Issue report?

Thank you.

**Comment by balazsrm** [comment]
Hi @DAnn2012,
Thank you for bringing these issues to our attention. We'll get them fixed in an update soon.

**Comment by pratikrm** [comment]
Hi @DAnn2012 

We have fixed this issue in v1.0.225.

**Comment by DAnn2012** [comment]
Hi @pratikrm 

Thank you for the reply.

I had already noticed this, but I see that the file "`/assets/admin/js/classic.js`" has been updated with the changes and therefore the files that are in the path "`/assets/admin/src/classic/`" are to be considered obsolete?

Thanks.

**Comment by pratikrm** [comment]
Hi @DAnn2012 

The files in the assets/admin/src directory are source files that are not executed directly by the plugin. These source files are compiled using a compiler into the assets/admin/js folder, and the compiled files are then used by the plugin.
