### ISSUE TITLE
Publish RankMath Pro on WP Packagist?

### ISSUE THREAD

**Issue by davidhund** [rankmath/seo-by-rank-math#30]
@surajv - (Please excuse me for double-posting. My previous comment was in a closed topic and I'm not sure it shows up)

I am using Composer `wpackagist-plugin/seo-by-rank-math` to install RM (Free) but am now looking at installing Pro: I cannot find Pro on wpackagist, is this correct?

Ideally I could install both with:

```
"require": {
  ...
  "wpackagist-plugin/seo-by-rank-math": "^1.0",
  "wpackagist-plugin/seo-by-rank-math-pro": "^2.0",
  ...
}
```

I understand one does not need a License key (but connect our sites) so it seems fine to publish the Pro version on Wpackagist...

**Comment by surajv** [comment]
Hello @davidhund,

Sorry for the delayed response, unfortunately, we can't publish the pro version. 

But we have a workaround. Please open a ticket on our support forum, we will share the details.

Thank you.
