### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by techgarageblog** [rankmath/seo-by-rank-math#38]
I`m new RankMath Customer and actually there are a lot of issue in my Error Log. 

One of this is:

2020/12/03 09:05:51 [error] 55610#55610: *423324 FastCGI sent in stderr: "PHP message: PHP Warning: sprintf(): Too few arguments in /www/techgarageblog_551/public/wp-content/plugins/seo-by-rank-math/includes/modules/seo-analysis/seo-analysis-tests.php on line 55" while reading response header from upstream, client: 66.249.64.72, server: techgarage.blog, request: "GET /wp-admin/admin-ajax.php?action=wl_navigator&uniqid=wl-navigator-widget-5fc8a85a6dcb9&post_id=101962&limit=4&offset=0&sort=ID%20DESC HTTP/1.0", upstream: "fastcgi://unix:/var/run/php7.4-fpm-techgarageblog.sock:", host: "techgarage.blog", referrer: "https://techgarage.blog/pixelmator-photo-die-bildbearbeitungs-app-fuer-das-ipad-kann-ab-sofort-vorbestellt-werden/?trk=organization-update-content_share-video-embed_share-article_title"
--
 
![CleanShot 2020-12-03 at 10 10 09](https://user-images.githubusercontent.com/45080766/100988267-d492a180-354f-11eb-98b9-5fa65d71100b.png)

I wrote already with the Team from the wl_navigator (Wordlift) and they mean the error is related to you.

The other issue is this:

The next one is this
2020/12/03 07:39:06 [error] 55613#55613: *420768 FastCGI sent in stderr: "PHP message: PHP Warning: Illegal string offset 'title' in /www/techgarageblog_551/public/wp-content/plugins/seo-by-rank-math-pro/includes/modules/schema/class-admin.php on line 399PHP message: PHP Warning: Illegal string offset 'id' in /www/techgarageblog_551/public/wp-content/plugins/seo-by-rank-math-pro/includes/modules/schema/class-admin.php on line 400PHP message: PHP Warning: Illegal string offset 'title' in /www/techgarageblog_551/public/wp-content/plugins/seo-by-rank-math-pro/includes/modules/schema/class-admin.php on line 399PHP message: PHP Warning: Illegal string offset 'id' in /www/techgarageblog_551/public/wp-content/plugins/seo-by-rank-math-pro/includes/modules/schema/class-admin.php on line 400" while reading response header from upstream, client: 2001:1620:6ed:0:1df6:da7d:220e:3564, server: techgarage.blog, request: "GET /wp-admin/post-new.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php7.4-fpm-techgarageblog.sock:", host: "techgarage.blog", referrer: "https://techgarage.blog/wp-admin/edit.php"

**Comment by balazsmts** [comment]
The first error, `` is due to a problem in the german translation for the plugin. The original string is this:
`For the best SEO results, use a custom permalink structure, preferably one that includes the post title (<code>%%postname%%</code>). You can change it by navigating to <a href=\"%s\">Settings &gt; Permalinks</a>`

The translated version is this:
`Für die besten SEO-Ergebnisse verwenden Sie eine benutzerdefinierte Permalink-Struktur, vorzugsweise eine, die den Posttitel enthält (<code>%%%postname%%%</code>). Du kannst es ändern, indem du zu <a href=\"%s\">Einstellungen &gt; Permalinks</a> navigierst`

Notice the extra `%` in `%%%postname%%%`, that is what's causing the error.

**Comment by balazsmts** [comment]
The second set of errors, `PHP Warning: Illegal string offset` seems to be related to Rank Math Pro. I'm transferring that issue to the Pro repo.

**Comment by techgarageblog** [comment]
Thank you. Did you already fix the translation bug on your site?

**Comment by surajv** [comment]
We have submitted the translated version on WordPress.org https://translate.wordpress.org/projects/wp-plugins/seo-by-rank-math/stable/de/default/?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=waiting&filters%5Buser_login%5D=rankmath

Waiting for editors to approve it. If you anyone, please inform them.

Thank you.

**Comment by surajv** [comment]
Translation approved, closing it.
