### ISSUE TITLE
Why need FB secret?

### ISSUE THREAD

**Issue by thegulshankumar** [rankmath/seo-by-rank-math#6]
https://github.com/rankmath/seo-by-rank-math/blob/653b0e055c5cecf02dfc683f7964f1e1db121ad0/includes/admin/metabox/class-metabox.php#L282

When scraping can be done with GET request at below form of URL

`https://graph.facebook.com/?id=[URL]&scrape=true`

**Comment by surajv** [comment]
Hello @thegulshankumar,

It is a required parameter along with the `id` parameter, please refer this document https://developers.facebook.com/docs/graph-api/reference/v8.0/url (**Query String Parameters** section)

Here is the source code where we use the secret https://github.com/rankmath/seo-by-rank-math/blob/master/includes/admin/metabox/class-metabox.php#L301

Hope this helps.

**Comment by thegulshankumar** [comment]
In the Query String Parameters section, there is no mention of `App Secret` word at any place. 

Is it like App Secret used for generating App Access Token?

**Comment by surajv** [comment]
Yes, to generate Access Token, you need an App ID and Secret, please refer to this document: https://developers.facebook.com/docs/facebook-login/access-tokens/#apptokens (**Generating an App Access Token** section)
