### ISSUE TITLE
Error detecting minified files from LiteSpeed Cache

### ISSUE THREAD

**Issue by ribeiroeder** [rankmath/seo-by-rank-math#65]
Rank Math Seo Analysis wrongly (false positive) marks LiteSpeed Cache's optimized and compressed files as "not minified"

![dont-detect-minify](https://user-images.githubusercontent.com/24439523/110978511-3bd7a300-8342-11eb-9fd0-d0a7ba8ab79c.jpg)

thanks!

**Comment by ribeiroeder** [comment]
Below is no longer an error, but it deserves a note:

I think google fonts should be white-listed and not on the list, since they don't offer minified fonts.

![gfonts](https://user-images.githubusercontent.com/24439523/110981182-8e668e80-8345-11eb-97b1-ac8e8b6bcc20.jpg)

**Comment by balazsmts** [comment]
Hello @ribeiroeder 

Thank you for your suggestions. We have made some changes in our Analysis API, and these things you shared should not cause the tests to fail anymore.

Hope that helps. If there's any issue, please let us know.

**Comment by ribeiroeder** [comment]
Hello @balazsmts

Thank you for your attention! I'm closing the topic.
