### ISSUE TITLE
Filter for og:updated_time

### ISSUE THREAD

**Issue by shazahm1** [rankmath/seo-by-rank-math#71]
**Is your feature request related to a problem? Please describe.**
No, I need a filter to dynamically adjust the updated_time OG tag.

**Describe the solution you'd like**
Please add a filter here:

- https://github.com/rankmath/seo-by-rank-math/blob/v1.0.60.1/includes/opengraph/class-facebook.php#L318

**Describe alternatives you've considered**
No filter exists.

**Additional context**
None.

**Comment by surajv** [comment]
Hi @shazahm1,

You can use this filter:

```
add_filter( "rank_math/opengraph/facebook/og_updated_time", function( $content ) {
	return 'NEW VALUE';
});
```
Reference: https://rankmath.com/kb/filters-hooks-api-developer/#change-specific-social-meta

I hope this helps.

Thank you.

**Comment by shazahm1** [comment]
Yes, thanks; I just came back to close because I had just found the filter.
