### ISSUE TITLE
v1.0.62 — Schema Snippet class-primaryimage.php: `Undefined offset: 0` warning

### ISSUE THREAD

**Issue by davidhund** [rankmath/seo-by-rank-math#75]
**Describe the bug**
After updating to v1.0.62 My homepage (only) showed the warning:

```
Notice: Undefined offset: 0 
in /[...]/seo-by-rank-math/includes/modules/schema/snippets/class-primaryimage.php on line 38
```
https://github.com/rankmath/seo-by-rank-math/blame/master/includes/modules/schema/snippets/class-primaryimage.php#L38

The variable `$image` at this point is an Array with _only_ a `caption` key _and no value_:

```
Array ( [caption] => )
```

**Desktop (please complete the following information):**
 - OS: OSX
 - Firefox 87.0

**Additional context**
This is a **MultiSite**, Multi-Language-Press Wordpress 5.7 install.
The error *only* occurs on the root `site.com/`

**Comment by surajv** [comment]
Fixed in v1.0.63
