### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by kyloknight** [rankmath/seo-by-rank-math#77]
**Describe the bug**

File: `seo-by-rank-math/includes/modules/schema/class-admin.php` 
Line: 305

```
private function get_schema_types( $post_id ) {
        $schemas = DB::get_schemas( $post_id );
        if ( empty( $schemas ) ) {
            return false;
        }
 
        $types = [];
        foreach ( $schemas as $schema ) {
            $types[] = Helper::sanitize_schema_title( $schema['@type'] );
        }
 
        return implode( ', ', $types );
    }
```

Conditional needed above when "$schema" returns false.

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Comment by surajv** [comment]
Hi @po8digital, could you please confirm if this error is happening with the latest version?

Thank you.

**Comment by pratikmts** [comment]
Closing it due to inactivity. Please reopen it if you still get an error.
