### ISSUE TITLE
Publish on Packagist

### ISSUE THREAD

**Issue by Log1x** [rankmath/seo-by-rank-math#8]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like to see if you guys could publish Rank Math on Packagist.org real quick – everything in the repo is already setup so it just needs someone with access to [mythemeshop](https://packagist.org/packages/submit?query=mythemeshop) to add it

**Comment by surajv** [comment]
Hi Brandon,

That sounds interesting, how are you planning to use it. So we can test the scenario on our end before putting it as a package?

Thank you.

**Comment by Log1x** [comment]
It's more or less be used with https://roots.io/bedrock/ (which manages plugins via Composer)

Also see: https://wpackagist.org/

**Comment by surajv** [comment]
oh okay, added here https://packagist.org/packages/rankmath/seo-by-rank-math

Hope this helps.

**Comment by Log1x** [comment]
appreciate it!

**Comment by Log1x** [comment]
https://github.com/rankmath/seo-by-rank-math/blob/master/composer.json#L17 is causing CMB2 to be installed as a plugin

**Comment by surajv** [comment]
Hi Brandon,

Sorry for the delay. We were busy with today's update, will get back to you by tomorrow.

Thank you.

**Comment by surajv** [comment]
You might need to disable that using this plugin https://github.com/lukasbesch/bedrock-plugin-disabler

**Comment by Log1x** [comment]
bedrock-plugin-disabler is more so for disabling plugins based on your current WordPress environment.

I think the fix might be moving cmb2 to `require-dev` in `composer.json` since it is otherwise bundled + committed in the repo.

**Comment by surajv** [comment]
Unfortunately, CMB2 is a required package, and it needs to be bundled in the plugin. RM will not work without it, as we create the plugin's Options Panel and Classic Editor options using the CMB2 library.

**Comment by Log1x** [comment]
With CMB2 being committed [into the repo](https://github.com/rankmath/seo-by-rank-math/tree/master/vendor) – it will still work as intended.

**Comment by surajv** [comment]
Got it! Pushed the changes along with the new minor update.

Please confirm.

**Comment by Log1x** [comment]
Hmm I was wrong. It does need to be in `require`

https://salferrarello.com/cmb2-composer-dependency/ I believe this method should work.

**Comment by surajv** [comment]
Please confirm these changes https://github.com/rankmath/seo-by-rank-math/pull/11/files

**Comment by surajv** [comment]
Hi Brandon, did you get time to check this?

**Comment by d0ky** [comment]
Just a quick questione: would you pubblish on wpackagist as well at the end?

**Comment by surajv** [comment]
Hi @d0ky,

It is available now https://wpackagist.org/search?q=seo-by-rank-math&type=plugin&search=

**Comment by surajv** [comment]
Closing it for the inactivity of OP.

**Comment by davidhund** [comment]
@surajv - (Excuse me for posting in a closed topic)

I am using Composer `wpackagist-plugin/seo-by-rank-math` to install RM (Free) but am now looking at installing Pro: I cannot find Pro on wpackagist, is this correct?

Ideally I could install both with:

```
"require": {
  ...
  "wpackagist-plugin/seo-by-rank-math": "^1.0",
  "wpackagist-plugin/seo-by-rank-math-pro": "^2.0",
  ...
}
```

I understand one does not need a License key (but _connect_ our sites) so it seems fine to publish the Pro version on Wpackagist...
