### ISSUE TITLE
Rank Math SEO pushes Create by Mediavine header down by 6px

### ISSUE THREAD

**Issue by jesgs** [rankmath/seo-by-rank-math#88]
Hi there! I’m a developer for the Create by Mediavine plugin and our team has recently discovered a styling issue when using Create in conjunction with Rank Math SEO.

We've found that adding `max-height: 20px` to `#wp-admin-bar-rank-math .rank-math-icon` located at seo-by-rank-math/includes/admin/class-admin-menu.php:117 fixes the problem without causing styling issues for the icon.

Including a related PR that includes the styling addition above.

Thanks for your time! 

—Jess

**Describe the bug**
The issue is the styling on the Rank Math SEO icon in the WordPress admin bar (see attached screenshot). The top: 6px positioning of the Rank Math SEO icon in the WP adminbar is causing Create's header to be pushed down by 6 pixels—you can see this in action on the All Create Cards screen, or any of the Recipe, How-To, or List edit screens.

**To Reproduce**

1. Download and activate Create with Rank Math SEO already active
2. Navigate to All Create Cards
3. Observe the Create header
4. Create header sits 6 pixel gap between the WordPress admin bar and the Create header

**Expected behavior**
The Create header should sit against the WordPress admin bar even if Rank Math SEO is active

**Screenshots**
Currently:
<img width="511" alt="Screen Shot 2021-07-29 at 11 27 01 AM" src="https://user-images.githubusercontent.com/2304490/128411440-4a6fe5e3-bbf5-4ce6-835c-9be2e4a92d4e.png">

With fix applied:
<img width="341" alt="Screen Shot 2021-08-05 at 2 45 23 PM" src="https://user-images.githubusercontent.com/2304490/128411578-130aa818-d927-4cee-90dc-6f1c58abb315.png">

**Desktop (please complete the following information):**
- OS: MacOS 10.15.7

**Browsers:**
- Chrome 92.0.4515.107
- Safari 14.1.1
- Firefox 90.0.2

**Additional context**
See PR #89

**Comment by pratikmts** [comment]
Closing this issue as it has been fixed in v1.0.77
