### ISSUE TITLE
Woo-commerce product section breaks after activating Rankmath SEO 

### ISSUE THREAD

**Issue by Rink9** [rankmath/seo-by-rank-math#96]
**Bug Name**
Woo-commerce Product section breaks after activating Rank Math SEO.

**To Reproduce**
1. Activate Woo-commerce
2. Activate Rank Math SEO
3. Go to /wp-admin/edit.php?post_type=product
4. View product SEO details section

**Screenshots**
<img width="1425" alt="Rankmathproduct" src="https://user-images.githubusercontent.com/44554636/135998447-3025770e-07aa-4c4b-8413-8dc521de4ed8.png">

**Desktop :**
 - OS: macOS Version 11.5.2
 - Browser : Chrome
 - Version : 94.0.4606.61 (Official Build) (x86_64)

**Comment by surajv** [comment]
Hello @Rink9,

Thank you for creating an issue. This is not a bug, and it can be easily fixed.

Please refer to this KB https://rankmath.com/kb/woocommerce-products-page-misaligned/
