### ISSUE TITLE
Warning: Illegal string offset '@type' in schema\class-admin.php on line 207

### ISSUE THREAD

**Issue by codetot** [rankmath/seo-by-rank-math#98]
**Describe the bug**

```
Warning: Illegal string offset '@type' in wp-content\plugins\seo-by-rank-math\includes\modules\schema\class-admin.php on line 207
```

**To Reproduce**
1. Install RankMath
2. In Setup Guide, just skip all steps.
3. Migrate posts from old site (which has Rank Math data) using WP All Import plugin (add all custom fields)
4. Navigate to Posts after migrating.

**Screenshots**

<img width="540" alt="Screenshot_2" src="https://user-images.githubusercontent.com/68487935/137696017-5fcdaf32-d194-41e7-8503-3353b59cbd0e.png">

**Additional context**

I believe your code check `empty($schemas)` is not good cover in this case. In my dump data, it loads:

```
'schema-177880' => string '' (length=0)
  'schema-177883' => string '' (length=0)
  'schema-177922' => string '' (length=0)
  'schema-177938' => string '' (length=0)
```

**Comment by surajv** [comment]
@codetot could you please udpate to the latest version and check again?

Thank you.
